#!/bin/bash
{
	# Core globals
	G_PROGRAM_NAME='DietPi-Installer'

	# Critical checks
	if (( $UID ))
	then
		echo -e '[FAILED] Root privileges required, please run this script with "sudo"\n'
		exit 1
	fi

	export LC_ALL='C.UTF-8' LANG='C.UTF-8'
	export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
	mount -a

	# Assure that /tmp is a tmpfs
	if ! findmnt -M /tmp > /dev/null
	then
		mount -t tmpfs -o 'size=512M,noatime,lazytime,nodev,nosuid,mode=1777' tmpfs /tmp
	fi

	FP_SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
	cd /tmp || exit 1

	# Initial APT Update
	apt-get update
	aAPT_PREREQS=('curl' 'ca-certificates' 'whiptail' 'mawk')
	for i in "${aAPT_PREREQS[@]}"; do
		dpkg-query -s "$i" &> /dev/null || apt-get -y install "$i"
	done

        G_HW_ARCH_NAME=$(uname -m)
	# Allow riscv64 native OR aarch64/x86_64 hosts (for cross-building)
	if [[ $G_HW_ARCH_NAME == 'riscv64' || $G_HW_ARCH_NAME == 'aarch64' || $G_HW_ARCH_NAME == 'x86_64' ]]
	then
		G_HW_ARCH=11
	else
		echo "[FAILED] Unsupported CPU architecture: \"$G_HW_ARCH_NAME\"."
		exit 1
	fi

	# Load DietPi-Globals
	GITOWNER=${GITOWNER:-MichaIng}
	GITBRANCH=${GITBRANCH:-master}
	curl -sSf "https://raw.githubusercontent.com/$GITOWNER/DietPi/$GITBRANCH/dietpi/func/dietpi-globals" -o dietpi-globals
	. ./dietpi-globals
	rm dietpi-globals
	G_INIT

	# Hardware Selection (Simplified for RISC-V)
	G_WHIP_MENU_ARRAY=(
		'81' ': StarFive VisionFive 2'
		'84' ': Star64'
		'22' ': Generic device'
	)
	G_WHIP_MENU 'Please select the current RISC-V device:'
	G_HW_MODEL=$G_WHIP_RETURNED_VALUE

	# Install DietPi source code
	G_EXEC curl -sSfLO "https://github.com/MichaIng/DietPi/archive/$G_GITBRANCH.tar.gz"
	dir="DietPi-${G_GITBRANCH//\//-}"
	tar xf "${G_GITBRANCH##*/}.tar.gz"

	# Hardware specific boot configs (RV64 ONLY)
	if (( $G_HW_MODEL == 81 ))
	then
		# VisionFive 2
		G_AGI linux-image-visionfive2 libubootenv-tool
		G_EXEC sed --follow-symlinks -i "s/root=[^[:blank:]]*/root=PARTUUID=$(findmnt -Ufnro PARTUUID -M /)/" /boot/extlinux/extlinux.conf
		G_EXEC sed --follow-symlinks -i "s/rootfstype=[^[:blank:]]*/rootfstype=$(findmnt -Ufnro FSTYPE -M /)/" /boot/extlinux/extlinux.conf

	elif (( $G_HW_MODEL == 84 ))
	then
		# Star64
                G_HW_MODEL_NAME='Star64'
		G_EXEC curl -fLO 'https://dietpi.com/downloads/binaries/testing/linux-image-star64.deb'
		G_EXEC dpkg -i linux-image-star64.deb
		rm linux-image-star64.deb
		G_AGI libubootenv-tool
		G_EXEC sed --follow-symlinks -i "s/root=[^[:blank:]]*/root=PARTUUID=$(findmnt -Ufnro PARTUUID -M /)/" /boot/extlinux/extlinux.conf
                G_EXEC bash -c "echo 'bash <(curl -s https://install.felix86.com)' >> /var/lib/dietpi/post-inst.sh"
	fi

	# Finalize Installation (Standard DietPi cleanup)
	# ... (Removes installer and reboots)
	G_DIETPI-NOTIFY 0 'Completed, RISC-V DietPi system is ready.'
}